### PR TITLE
Timot mar test 2

### PR DESCRIPTION
**Pull request by TimotMar**
Adding comments so the code is more understandable

### CODE REVIEW

**Comment by TimotMar** [comment]
adding PSR 2 standards coding

**Comment by eddymio** [comment]
Still a few bunch or errors with php-cs-fixer 
   1) Blogdev//index.post.php (line_ending, braces, single_blank_line_at_eof)
   2) Blogdev//model/Manager.php (line_ending, single_blank_line_at_eof)
   3) Blogdev//model/login.php (line_ending, braces)
   4) Blogdev//model/config/database.php (line_ending, method_argument_space, braces)
   5) Blogdev//model/logout.php (line_ending, no_closing_tag, single_blank_line_at_eof)
   6) Blogdev//model/activation.php (no_spaces_after_function_name, line_ending, braces, single_blank_line_at_eof)
   7) Blogdev//model/share_code.php (line_ending, braces)
   8) Blogdev//model/profile.php (line_ending, braces, single_blank_line_at_eof)
   9) Blogdev//model/edit_user.php (line_ending, braces, single_blank_line_at_eof)
  10) Blogdev//model/microposts.php (line_ending, braces, single_blank_line_at_eof)
  11) Blogdev//model/register.php (no_spaces_after_function_name, line_ending, braces)
  12) Blogdev//model/PostManager.php (line_ending, single_blank_line_at_eof)
  13) Blogdev//model/list_users.php (line_ending, single_blank_line_at_eof)
  14) Blogdev//model/show_code.php (line_ending, braces)
  15) Blogdev//model/CommentManager.php (line_ending, single_blank_line_at_eof)
  16) Blogdev//views/micropost.view.php (braces)
  17) Blogdev//views/modifier.php (line_ending, braces)
  18) Blogdev//views/register.view.php (line_ending)
  19) Blogdev//views/form_to_email_script.php (line_ending, method_argument_space, braces)
  20) Blogdev//views/partials/_header.php (line_ending)
  21) Blogdev//views/partials/_menu.php (no_spaces_inside_parenthesis, braces)
  22) Blogdev//views/partials/_flash.php (line_ending, braces)
  23) Blogdev//views/partials/_errors.php (line_ending, braces, single_blank_line_at_eof)
  24) Blogdev//views/login.view.php (line_ending)
  25) Blogdev//views/edit_user.view.php (line_ending, no_trailing_whitespace, braces)
  26) Blogdev//views/list_users.view.php (no_trailing_whitespace_in_comment)
  27) Blogdev//views/profile.view.php (line_ending)
  28) Blogdev//views/frontend/postView.php (line_ending, braces)
  29) Blogdev//views/frontend/listPostsView.php (line_ending, braces)
  30) Blogdev//bootstrap/local.php (line_ending, braces, single_blank_line_at_eof)
  31) Blogdev//controller/frontend.php (line_ending, braces)
  32) Blogdev//controller/includes/constants.php (no_spaces_after_function_name, line_ending, method_argument_space, single_blank_line_at_eof)
  33) Blogdev//controller/includes/functions.php (no_spaces_after_function_name, function_declaration, line_ending, braces, single_blank_line_at_eof)
  34) Blogdev//controller/filter/user_filter.php (line_ending, no_closing_tag, braces, single_blank_line_at_eof)
  35) Blogdev//controller/filter/guest_filter.php (line_ending, braces)
  36) Blogdev//index.php (line_ending)
  37) Blogdev//seed/users.php (line_ending, braces, single_blank_line_at_eof)
  38) Blogdev//locals/menu.php (line_ending)
  39) Blogdev//test.php (line_ending, single_blank_line_at_eof)

**Comment by eddymio** [comment]
For the comments, that is better, I'm sure you can do more :) For instance on top of each file you can add a note to tell us more about the purpose of the lines ie : add phpdoc style comments on top of each class (https://docs.phpdoc.org/) in the model package.

I still see some french words...

**Comment by eddymio** [comment]
My bad, I wasn't on the right branch but comments still applied.
More about the code now : I see some kind of inconsistency in the code, for instance you are using both Manager.php and database.php

Then you use POO for comments and posts but not users, why ? This is the kind of question you will likely meet during the "soutenance"... I know the answer but if you have time to look into such feature, that would be great !
Same things apply for the controller parts where you load the view sometimes, but not all the time, I can see some view loading right into your model files...

**Pull request merged**
